### ISSUE TITLE
BufferedReader (missing Discard method)

### ISSUE THREAD

**Issue by bclermont** [dsnet/compress#25]
I just tried to go get in golang 1.4.2:

```
$ go get github.com/dsnet/compress
# github.com/dsnet/compress
go/src/github.com/dsnet/compress/api.go:52: cannot use (*bufio.Reader)(nil) (type *bufio.Reader) as type BufferedReader in assignment:
	*bufio.Reader does not implement BufferedReader (missing Discard method)
```

**Comment by dsnet** [comment]
Hey, thanks for the report. Unfortunately, this package only works for ```go1.5``` and above. The bufio.Reader.Discard method was necessary for higher performance while decompressing. That being said, there is a way to wrap bufio.Reader in a way and get it to work, but the solution is kinda dirty.

Are you able to use Go1.5?

**Comment by dsnet** [comment]
Closing this. I added a mention on the README that 1.5+ is required for the library.
