### ISSUE TITLE
Empty files produce invalid bz2 files

### ISSUE THREAD

**Issue by rikonor** [dsnet/compress#57]
Hi,

The following will generate an invalid bzip2 file:

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/dsnet/compress/bzip2"
)

func main() {
	f, err := os.Create("test.bz2")
	if err != nil {
		log.Fatal(err)
	}

	w, err := bzip2.NewWriter(f, &bzip2.WriterConfig{Level: 2})
	if err != nil {
		log.Fatal(err)
	}
	defer w.Close()

	// fmt.Fprint(w, "test")
}
```

Resulting in:
```
➜  tmp bzip2 -d test.bz2
bzip2: test.bz2 is not a bzip2 file.
```

Uncommeting `fmt.Fprint(w, "test")` will produce a valid bz2.

**Comment by dsnet** [comment]
Hi @rikonor, thanks for the bug report. I was able to reproduce this on the `master` branch, but it seems that I [have already fixed this problem](https://github.com/dsnet/compress/commit/6c48adecf3e0ba52d9f3e39c0267802691399cea) on the `development` branch. I plan on merging `development` into `master` in the near future. There are other bug fixes other than just this one.

In the mean time, can you use the `development` branch instead?

**Comment by rikonor** [comment]
Hi @dsnet, sounds good. Did not realize it was fixed in `development`. Thanks for the quick response!
