### ISSUE TITLE
xflate: behavior for reading past stream end

### ISSUE THREAD

**Issue by Lupus** [dsnet/compress#71]
Does xflate track the total size of uncompressed stream? Is it possible to read past the end of the stream somehow?

**Comment by dsnet** [comment]
Assuming that the input file is not corrupted or maliciously crafted, it is impossible to read past the end of the stream. 

In [section 2.1](https://github.com/dsnet/compress/blob/master/doc/xflate-format.pdf) of the specification, you can see that the index contains the total "raw" size. The "raw" size is the size of the uncompressed data.

**Comment by Lupus** [comment]
Great, thanks for confirming!
